eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign


  #mvc:
  #  view:
      #    prefix: /WEB-INF/view/
    #    suffix: .jsp
feign:
  hystrix:
    enabled: true

